SHELL := /bin/bash

all : webapp/combined.js

webapp/combined.js : webapp/data_structures/*.js
	@echo generating $@ ...
	@( echo '/* This file is autogenerated. Do not edit this file. */'; cat $(sort $^) ) > $@

flake8 :
	@flake8 --statistics --extend-exclude 'env*'
